project:
  type: website

website:
  title: ""
  navbar:
    left:
      - href: index.qmd
        text: Home
  sidebar:
    contents: auto

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-tools: true
    
highlight-style: monokai



